version: 0.2
os: linux
phases:
    build:
      commands:
      - echo build started in `date`
      - cd lib
      - zip -r9 ../deployment_package.zip
      - cd ..
      - zip -g deployment_package test.py
      - echo compiling the python code
      - echo this is my code
      - pip install pandas
      - echo pandas library is installed
    post_build:
      commands:
      - echo build completed on `date`
      - aws lambda update-fuction-code --function-name test-lambda --zip-file fileb://deployment_package.zip
      - pwd
      - ls 
artifacts:
    files:
      '**/*'
