version: 0.2
os: linux
phases:
    build:
      commands:
      - echo build started in `date`
      - echo compiling the python code
      - echo this is my code
      - pip install pandas
      - echo pandas library is installed
    post_build:
      commands:
      - echo build completed on `date`
      - pwd
      - ls 
artifacts:
    files:
      '**/*'
